// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ---------------------- WEB ----------------------
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMLeF7H-_ShK6rduua7S84-67vb94KOBQ',
    appId: '1:927203816352:web:d5831391af2e78e2b9eac5',
    messagingSenderId: '927203816352',
    projectId: 'agrosoft-3d8d2',
    authDomain: 'agrosoft-3d8d2.firebaseapp.com',
    storageBucket: 'agrosoft-3d8d2.appspot.com',
  );

  // ---------------------- ANDROID ----------------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs34tLSJ_ZqsB4Nc_hISEMeMtpYSYIiLE',
    appId: '1:927203816352:android:f4b34430e1f65613b9eac5',
    messagingSenderId: '927203816352',
    projectId: 'agrosoft-3d8d2',
    storageBucket: 'agrosoft-3d8d2.appspot.com',
  );

  // ---------------------- iOS ----------------------
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Qcicvs5zpGHIorkcwe-OPl6QPPerFhM',
    appId: '1:927203816352:ios:2175d5f5980d2ba0b9eac5',
    messagingSenderId: '927203816352',
    projectId: 'agrosoft-3d8d2',
    storageBucket: 'agrosoft-3d8d2.appspot.com',
    iosClientId:
        '927203816352-4jprp58b9dfrd7d51r1s967f134i56uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrosoft',
  );

  // ---------------------- MACOS ----------------------
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Qcicvs5zpGHIorkcwe-OPl6QPPerFhM',
    appId: '1:927203816352:ios:2175d5f5980d2ba0b9eac5',
    messagingSenderId: '927203816352',
    projectId: 'agrosoft-3d8d2',
    storageBucket: 'agrosoft-3d8d2.appspot.com',
    iosClientId:
        '927203816352-4jprp58b9dfrd7d51r1s967f134i56uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.agrosoft',
  );

  // ---------------------- WINDOWS ----------------------
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMLeF7H-_ShK6rduua7S84-67vb94KOBQ',
    appId: '1:927203816352:web:1145d0577d7d8d9bb9eac5',
    messagingSenderId: '927203816352',
    projectId: 'agrosoft-3d8d2',
    authDomain: 'agrosoft-3d8d2.firebaseapp.com',
    storageBucket: 'agrosoft-3d8d2.appspot.com',
  );
}
